apiVersion: v1
kind: Secret
metadata:
  name: diego-api
  namespace: diego
type: Opaque
stringData:
  ARGOCD_API: https://argocd.core.{{{ DOMAIN }}}
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: {{{ ARGOCD_PASSWORD }}}
  AUTH0_DOMAIN: https://diegocloud.eu.auth0.com/
  AUTH0_AUDIENCE: https://diego-api.core.{{{ DOMAIN }}}
  GITHUB_REPO_OWNER: {{{ ORG_NAME }}}
  GITHUB_REPO_NAME: default-project
  GIN_MODE: release
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app
  namespace: diego
type: Opaque
stringData:
  app_id: {{{ APP_ID }}}
  installation_id: {{{ APP_INSTALLATION_ID }}}
  org_name: {{{ ORG_NAME }}}
  app.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    {{{ GITHUB_APP_PEM_KEY }}}
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-github-oauth
  namespace: dex
type: Opaque
stringData:
  client_id: '{{{ APP_CLIENT_ID }}}'
  client_secret: '{{{ APP_CLIENT_SECRET }}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-static-clients-oauth
  namespace: dex
type: Opaque
stringData:
  argocd_client_id: 'argocd'
  argocd_client_secret: '{{{ ARGOCD_CLIENT_SECRET }}}'
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc
  namespace: argocd
type: Opaque
stringData:
  argocd_client_id: 'argocd'
  argocd_client_secret: '{{{ ARGOCD_CLIENT_SECRET }}}'