apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  destination:
    namespace: dex
    server: https://kubernetes.default.svc
  project: diego-tooling
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true    
  source:
    chart: dex
    repoURL: https://charts.dexidp.io
    targetRevision: 0.12.1
    helm:
      valueFiles:
      - values.yaml
      values: |
        envVars:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dex-oauth
                key: client_id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-oauth
                key: client_secret
          - name: ARGOCD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-oauth
                key: argocd_client_secret
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-oauth
                key: oauth2_proxy_client_secret

        config:

          # NOTE - all of the config below should be moved to a more secret location as this 
          #        contains confidential information about dex's client id and secret as 
          #        generated by Auth0 and also Argocd's client id and secret as authored here, 
          #        by dex

          issuer: https://dex.diego.{{{ DOMAIN }}}

          storage:
            type: memory

          oauth2:
            responseTypes: [ "code" ]
            skipApprovalScreen: true

          enablePasswordDB: false
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: $CLIENT_ID
                clientSecret: $CLIENT_SECRET
                orgs:
                - name: {{{ ORG_NAME }}}
                redirectURI: 'https://dex.diego.{{{ DOMAIN }}}/callback'

          staticClients:
          - id: argocd
            secretEnv: ARGOCD_CLIENT_SECRET
            name: argocd
            redirectURIs:
            - https://argocd.diego.{{{ DOMAIN }}}/auth/callback
          - id: oauth2-proxy
            secretEnv: OAUTH2_PROXY_CLIENT_SECRET
            name: oauth2-proxy
            redirectURIs:
            - https://hub.diego.{{{ DOMAIN }}}/oauth2/callback

        ingress:
          enabled: true
          className: alb

          annotations:
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready 
            alb.ingress.kubernetes.io/healthcheck-port: '5558'
            alb.ingress.kubernetes.io/healthcheck-protocol: HTTP

          hosts:
            - host: dex.core.{{{ DOMAIN }}}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - dex.core.{{{ DOMAIN }}}

