apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diego-core
  namespace: argocd  
spec:
  project: diego-tooling
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: diego
  source:
    chart: diego-core
    repoURL: https://diego-cloud-io.github.io/helm-charts/
    targetRevision: 0.19.0

    helm:
      releaseName: diego-api
      values: |
        diego_application_controller_crds:
          enabled: true
        
        diego_application_controller_webhooks:
          enabled: true

        diego_hub:
          image:
            repository: diegocloudio/diego-hub
            tag: main

        diegoapi:
          aws_diego_api_role_arn: "arn:aws:iam::{{{ AWS_ACCOUNT_ID }}}:role/DiegoAPIRole"
          host: diego-api.diego.{{{ DOMAIN }}}
          image:
            repository: diegocloudio/diego-api
            tag: main

        diego_application_controller:
          project_repo_name: diego-default-project
          aws_actions_role_arn: "arn:aws:iam::{{{ AWS_ACCOUNT_ID }}}:role/DiegoCIRole"
          aws_diego_app_controller_role_arn: "arn:aws:iam::{{{ AWS_ACCOUNT_ID }}}:role/DiegoAppControllerRole"
          aws_region: eu-west-2
          image:
            repository: diegocloudio/application-controller
            tag: main
          ingress_host_domain: diego.{{{ DOMAIN }}}
          argocd_host: argocd.diego.{{{ DOMAIN }}}
